# Generated by Django 4.0.3 on 2022-05-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaiView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Детальна інформація')),
            ],
            options={
                'verbose_name': 'Детальна інформація',
                'verbose_name_plural': 'Детальні інформації',
            },
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Тури'},
        ),
        migrations.AlterModelOptions(
            name='tourshots',
            options={'verbose_name': 'Фото з туру', 'verbose_name_plural': 'Фото з турів'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pols.tour', verbose_name='Titile'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pols.category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(upload_to='photos/&Y/%m/&d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='url',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='tourshots',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tourshots',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Фото з туру'),
        ),
    ]
