# Generated by Django 4.0.3 on 2022-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0002_detaiview_alter_tour_options_alter_tourshots_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaiview',
            name='photo_shots',
            field=models.ImageField(default=1, upload_to='photos_shots/&Y/%m/&d/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
