# Generated by Django 4.0.3 on 2022-06-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0003_detaiview_photo_shots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Детальна інформація')),
                ('photo_shots', models.ImageField(upload_to='photos_shots/&Y/%m/&d/', verbose_name='Фото з туру ')),
            ],
            options={
                'verbose_name': 'Детальна інформація',
                'verbose_name_plural': 'Детальні інформації',
            },
        ),
        migrations.DeleteModel(
            name='DetaiView',
        ),
    ]
