# Generated by Django 4.0.3 on 2022-06-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0004_detai_delete_detaiview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detai',
        ),
        migrations.AddField(
            model_name='tourshots',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pols.tour', verbose_name='Тур'),
            preserve_default=False,
        ),
    ]
