# Generated by Django 4.0.3 on 2022-06-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pols', '0005_delete_detai_tourshots_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='url',
        ),
        migrations.DeleteModel(
            name='TourShots',
        ),
    ]
